### ISSUE TITLE
phi syntax sugar is not tested

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#3691]
Currently, we don't know whether syntax sugar works as expected in `PhiSyntax`. How about we create an additional parametrized test, which will use YAML files with two fields in each one:

```yaml
sweet:
  {⟦ k(t) ↦ ⟦⟧ ⟧}
salty:
  {⟦ k ↦ ⟦ t ↦ ∅ ⟧ ⟧}
```

The test will parse the `salty` part and then print it back in sugared form. Also, the other way around.
